name: Open Telemetry CI/CD Action
description: Export CI/CD workflows to any endpoint compatible with OpenTelemetry
author: Corentin Musard

runs:
  using: node24
  main: dist/index.js

inputs:
  otlpEndpoint:
    description: The destination endpoint to export OpenTelemetry traces to
    required: true
  otlpHeaders:
    description: Network Headers for the destination endpoint to export OpenTelemetry traces to
    required: false
    default: ""
  otelServiceName:
    description: OpenTelemetry service name
    required: false
    default: ""
  githubToken:
    description: The repository token with Workflow permissions. i.e. secrets.GITHUB_TOKEN
    required: false
  runId:
    description: Workflow Run ID to Export. Defaults to env.GITHUB_RUN_ID
    required: false
  extraAttributes:
    description: Extra resource attributes to add to each span
    required: false
  tokenUrl:
    description: OAuth2 token endpoint URL for client_credentials flow
    required: false
    default: ""
  appName:
    description: OAuth2 client ID (application name) for client_credentials flow
    required: false
    default: ""
  apiKey:
    description: OAuth2 client secret (API key) for client_credentials flow
    required: false
    default: ""
  audience:
    description: OAuth2 audience for client_credentials flow
    required: false
    default: ""
outputs:
  traceId:
    description: The OpenTelemetry Trace ID of the root span

branding:
  icon: bar-chart-2
  color: green
